on:
  push:
    # Only deploy when the branch name matches one of these
    # You probably only need `main`, the others are provided to work with the lecture
    branches: ["main", "reference/*", "lecture/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22.x, cache: "npm" }
      - run: npm ci
      - run: npm run build
      - run: npm test
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - uses: actions/deploy-pages@v4

    permissions:
      id-token: write # to verify the deployment originates from an appropriate source
      pages: write # to deploy to Pages
      contents: read # to checkout private repositories
